- hosts: all
  remote_user: ec2-user
  become: yes

  vars:
      source_file: sanjeevkumarsr/world:{{IMAGE_TAG}}
      destination_file: /home/ec2-user/

      


  tasks:
  - name: Install Python 3 pip package
    yum:
        name: python3-pip
        state: present
  
  - name: Install Docker
    yum:
        name: docker.io
        state: present

  - name: Start Docker service
    service:
        name: docker
        state: started

  - name: Docker python package
    pip:
        name: docker-py
        state: present
        
  - name: Create a directory if it does not exist
    file:
          dest: "{{ destination_file }}"
          state: directory
          
  - name: copy files
    copy:
        src: ./ 
        dest: "{{ destination_file }}" 
          
  - name: Add the Node.js repository
    shell: 'curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash '

  - name: Install Node.js and npm
    yum:
        name: nodejs
        state: present

  - name: Install npm
    command: npm install -g gulp
    args:
        chdir: "{{ destination_file }}"
    
  - name: Install Angular
    npm:
        name: '@angular/cli'
        global: yes
        state: present
        
  - name: Install Process manager tool
    npm:
        name: pm2
        global: yes
        state: present

  - name: Start service
    command:  pm2 start npm -- start ./src/index.html --name "{IMAGE_TAG}-Service"
    args:
      chdir: "{{ destination_file }}"
