- hosts: all
  remote_user: ubuntu
  become: yes

  vars:
      source_file: /var/lib/jenkins/workspace/angularproject
      destination_file: /home/ubuntu/jsrealworld
      


  tasks:
  - name: Install Python 3 pip package
    apt:
        name: python3-pip
        state: present
  
  - name: Install Docker
    apt:
        name: docker.io
        state: present

  - name: Start Docker service
    service:
        name: docker
        state: started

  - name: Docker python package
    pip:
        name: docker-py
        state: present
        
  - name: Create a directory if it does not exist
    file:
          dest: "{{ destination_file }}"
          state: directory

  - name: copy files
    copy:
        src: "{{ source_file }}"
        dest: "{{ destination_file }}"
       
  - name: Add the Node.js repository
    shell: 'curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash '

  - name: Install Node.js and npm
    apt:
        name: nodejs
        state: present

  - name: Install npm
    command: npm install -g gulp
    args:
        chdir: "{{ destination_file }}"
    
  - name: Install Angular
    npm:
        name: '@angular/cli'
        global: yes
        state: present
        
  - name: Install Process manager tool
    npm:
        name: pm2
        global: yes
        state: present

  - name: pm2 command
    command: pm2 status

  - name: Start service
    command:  pm2 start npm -- start /src/index.html --name "{{IMAGE_TAG}}-Service"
    args:
      chdir: "{{ destination_file }}"
